

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AutismAppJam.Data
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Entities : DbContext
{
    public Entities()
        : base("name=Entities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }

    public DbSet<Application> Applications { get; set; }

    public DbSet<AspNetRole> AspNetRoles { get; set; }

    public DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }

    public DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }

    public DbSet<AspNetUser> AspNetUsers { get; set; }

    public DbSet<MBTITest> MBTITests { get; set; }

    public DbSet<Membership> Memberships { get; set; }

    public DbSet<Personality> Personalities { get; set; }

    public DbSet<Profile> Profiles { get; set; }

    public DbSet<Role> Roles { get; set; }

    public DbSet<User> Users { get; set; }

    public DbSet<OccupationalTrend> OccupationalTrends { get; set; }

}

}

