//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutismAppJam.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MBTITest
    {
        public MBTITest()
        {
            this.Users = new HashSet<User>();
        }
    
        public System.Guid MbtiTestId { get; set; }
        public string Responses { get; set; }
        public bool Completed { get; set; }
    
        public virtual MBTITest MBTITests1 { get; set; }
        public virtual MBTITest MBTITest1 { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
