//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutismAppJam.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personality
    {
        public Personality()
        {
            this.OccupationalTrends = new HashSet<OccupationalTrend>();
        }
    
        public string PersonalityType { get; set; }
        public string PersonalityName { get; set; }
        public string PersonalityDescription { get; set; }
    
        public virtual ICollection<OccupationalTrend> OccupationalTrends { get; set; }
    }
}
