INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Management', 'ISTJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Administration', 'ISTJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Law Enforcement', 'ISTJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Accounting', 'ISTJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Education', 'ISFJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Health Care', 'ISFJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Religious Settings', 'ISFJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Religion', 'INFJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Counseling', 'INFJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Teaching', 'INFJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Arts', 'INFJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Scientific/Technical', 'INTJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Computers', 'INTJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Law', 'INTJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Skilled Trades', 'ISTP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Agriculture', 'ISTP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Law Enforcement', 'ISTP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Military', 'ISTP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Technical', 'ISTP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Health Care', 'ISFP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Business', 'ISFP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Law Enforcement', 'ISFP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Counseling', 'INFP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Writing', 'INFP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Arts', 'INFP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Scientific/Technical', 'INTP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Marketing', 'ESTP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Skilled Trades', 'ESTP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Business', 'ESTP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Law Enforcement', 'ESTP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Health Care', 'ESFP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Teaching', 'ESFP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Child Care', 'ESFP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Skilled Trades', 'ESFP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Counseling', 'ENFP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Teaching', 'ENFP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Religion', 'ENFP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Arts', 'ENFP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Science', 'ENTP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Management', 'ENTP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Technology', 'ENTP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Arts', 'ENTP')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Management', 'ESTJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Administration', 'ESTJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Education', 'ESFJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Health Care', 'ESFJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Religion', 'ESFJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Religion', 'ENFJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Arts', 'ENFJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Teaching', 'ENFJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Management', 'ENTJ')
INSERT INTO OccupationalTrends (Occupation, PersonalityType) VALUES ('Leadership', 'ENTJ')